name: Publish (Modrinth)

on:
  workflow_dispatch:

jobs:
  build_and_publish:
    name: Build and publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Get mod version from Gradle
        uses: madhead/read-java-properties@latest
        id: mod_version
        with:
          file: gradle.properties
          property: mod_version
          default: 0.0.1

      - name: Get supported Minecraft version from Gradle
        uses: madhead/read-java-properties@latest
        id: supported_minecraft_version
        with:
          file: gradle.properties
          property: supported_minecraft_version
          default: 0.0.1

      - name: Print version string
        run: echo version string ${{ steps.mod_version.outputs.value }}+mc${{ steps.supported_minecraft_version.outputs.value }}

      - name: Get existing release
        uses: cardinalby/git-get-release-action@v1
        id: get_existing_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: v${{ steps.mod_version.outputs.value }}+mc${{ steps.supported_minecraft_version.outputs.value }}
          doNotFailIfNotFound: true

      - name: Check if an existing release with the same version exists
        if: steps.get_existing_release.outputs.tag_name == v${{ steps.mod_version.outputs.value }}+mc${{ steps.supported_minecraft_version.outputs.value }}
        run: exit 1

      - name: Setup JDK (Temurin 17)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Change Gradle wrapper permissions
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        run: ./gradlew build

      # https://github.com/marketplace/actions/mc-publish
      - name: Publish mod (Fabric)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          # Modrinth
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          name: ${{ steps.mod_version.outputs.value }} (${{ steps.supported_minecraft_version.outputs.value }})
          github-tag: v${{ steps.mod_version.outputs.value }}+mc${{ steps.supported_minecraft_version.outputs.value }}
          files: |
            fabric/build/libs/!(*-@(sources|dev-shadow|javadoc|transformProduction*).jar)
            fabric/build/libs/*-@(sources|javadoc).jar
          version-type: release
          modrinth-featured: false
          changelog-file: CHANGELOG_LATEST.md

      # https://github.com/marketplace/actions/mc-publish
      - name: Publish mod (Forge)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          # Modrinth
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          name: ${{ steps.mod_version.outputs.value }} (${{ steps.supported_minecraft_version.outputs.value }})
          github-tag: v${{ steps.mod_version.outputs.value }}+mc${{ steps.supported_minecraft_version.outputs.value }}
          files: |
            forge/build/libs/!(*-@(sources|dev-shadow|javadoc|transformProduction*).jar)
            forge/build/libs/*-@(sources|javadoc).jar
          version-type: release
          modrinth-featured: false
          changelog-file: CHANGELOG_LATEST.md

      # https://github.com/marketplace/actions/mc-publish
      - name: Publish mod (NeoForge)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          # Modrinth
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          name: ${{ steps.mod_version.outputs.value }} (${{ steps.supported_minecraft_version.outputs.value }})
          github-tag: v${{ steps.mod_version.outputs.value }}+mc${{ steps.supported_minecraft_version.outputs.value }}
          files: |
            neoforge/build/libs/!(*-@(sources|dev-shadow|javadoc|transformProduction*).jar)
            neoforge/build/libs/*-@(sources|javadoc).jar
          version-type: release
          modrinth-featured: false
          changelog-file: CHANGELOG_LATEST.md
